version: '2'
services:
  myztl7-app:
    image: myztl7
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl7-postgresql:5432/myztl7
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8078:8078
  myztl7-postgresql:
    extends:
      file: postgresql.yml
      service: myztl7-postgresql
